# Generated by Django 4.1.7 on 2023-03-12 18:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('country', models.CharField(max_length=55, null=True, verbose_name='Страна')),
                ('city', models.CharField(max_length=55, null=True, verbose_name='Город')),
                ('street', models.CharField(max_length=55, null=True, verbose_name='Улица')),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=55, verbose_name='Название товара')),
                ('version', models.CharField(max_length=55, null=True, verbose_name='Модель товара')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Название компании')),
                ('company_type', models.CharField(choices=[('F', 'Завод'), ('R', 'Розничная сеть'), ('E', 'Предприниматель')], default='F', max_length=1, verbose_name='Тип компании')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='market.businessunit', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'BusinessUnit',
                'verbose_name_plural': 'BusinessUnit',
            },
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('duty', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Задолженность поставщику')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.businessunit')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.contact')),
                ('product', models.ManyToManyField(to='market.product')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'verbose_name_plural': 'BaseModel',
            },
        ),
    ]
